services:
  postgres:
    image: postgres:13
    container_name: budgetbook_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: budgetbook/budget-book-backend:latest
    container_name: budgetbook_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/budgetbook
      KEYCLOAK_REALM: budgetbook
      KEYCLOAK_CLIENT_ID: budgetbook-app
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: QDqaNEoz3reSsf7IpiG0VlohEBiA3RKF

  frontend:
    image: budgetbook/budget-book-frontend:latest
    container_name: budgetbook_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:

