style:
    ReturnCount:
        max: 4
    WildcardImport:
        active: false
    FunctionOnlyReturningConstant:
        active: false
    MagicNumber:
        excludes: [ '**/test/**', '**/integrationTest/**', '**/testdata/**' ]
    VarCouldBeVal:
        excludes: [ '**/test/**', '**/integrationTest/**', '**/testdata/**' ]

naming:
    FunctionNaming:
        excludes: [ '**/integrationTest/**','**/test/**', '**/testdata/**' ]

formatting:
    autoCorrect: true
    NoSemicolons:
        active: true
    NoWildcardImports:
        active: false
    MaximumLineLength:
        maxLineLength: 220

complexity:
    LargeClass:
        excludes: [ '**/integrationTest/**','**/test/**', '**/testdata/**' ]
    LongParameterList:
        active: false
    LongMethod:
        excludes: [ '**/integrationTest/**','**/test/**', '**/testdata/**' ]
    TooManyFunctions:
        excludes: [ '**/integrationTest/**','**/test/**', '**/testdata/**' ]
        ignorePrivate: true

potential-bugs:
    UnsafeCallOnNullableType:
        excludes: [ '**/integrationTest/**','**/test/**', '**/testdata/**' ]

exceptions:
    TooGenericExceptionThrown:
        active: false
    TooGenericExceptionCaught:
        active: false