name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    env:
      DATABASE_URL: postgres://user:password@localhost:5432/postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        working-directory: budget-book-backend
        run: ./gradlew build -x test -x integrationTest -x detektIntegrationTest

      - name: Run Unit Tests
        working-directory: budget-book-backend
        run: ./gradlew test

      - name: Run Integration Tests
        working-directory: budget-book-backend
        run: ./gradlew integrationTest

      #- name: Build Docker Image
      #  working-directory: budget-book-backend
      #  run: docker build -t budget-book-backend .

      #- name: Tag Docker Image
      #  run: docker tag budget-book-backend:latest ${{ secrets.DOCKER_USERNAME }}/budget-book-backend:latest

      - name: Build and Push Docker Image
        working-directory: budget-book-backend
        run: |
          docker buildx build --platform linux/amd64 \
          -t ${{ secrets.DOCKER_USERNAME }}/budget-book-backend:latest \
          --push .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        working-directory: budget-book-backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/budget-book-backend:latest
